Fix indentation in Argbash-generated code to match the script

diff --git a/bin/git-prw b/bin/git-prw
--- a/bin/git-prw
+++ b/bin/git-prw
@@ -41,6 +41,7 @@ EOF
 # ARG_POSITIONAL_SINGLE([REMOTE],[GitHub remote that the PR targets],[origin])
 # ARG_POSITIONAL_DOUBLEDASH([])
 # ARG_DEFAULTS_POS([])
+# ARGBASH_SET_INDENT([    ])
 # ARGBASH_GO()
 # needed because of Argbash --> m4_ignore([
 ### START OF CODE GENERATED BY Argbash v2.11.0 one line above ###
@@ -51,18 +52,18 @@ EOF
 
 die()
 {
-	local _ret="${2:-1}"
-	test "${_PRINT_HELP:-no}" = yes && print_help >&2
-	echo "$1" >&2
-	exit "${_ret}"
+    local _ret="${2:-1}"
+    test "${_PRINT_HELP:-no}" = yes && print_help >&2
+    echo "$1" >&2
+    exit "${_ret}"
 }
 
 
 begins_with_short_option()
 {
-	local first_option all_short_options='hvpf'
-	first_option="${1:0:1}"
-	test "$all_short_options" = "${all_short_options/$first_option/}" && return 1 || return 0
+    local first_option all_short_options='hvpf'
+    first_option="${1:0:1}"
+    test "$all_short_options" = "${all_short_options/$first_option/}" && return 1 || return 0
 }
 
 # THE DEFAULTS INITIALIZATION - POSITIONALS
@@ -76,109 +77,109 @@ _arg_force="off"
 
 print_help()
 {
-	printf '%s\n' "Facility to fetch a read/write branch from a GitHub repo Pull Request (PR).
+    printf '%s\n' "Facility to fetch a read/write branch from a GitHub repo Pull Request (PR).
 "
-	printf 'Usage: %s [-h|--help] [-v|--version] [-p|--protocol <arg>] [-f|--(no-)force] [--] <prID> [<REMOTE>]\n' "git prw"
-	printf '\t%s\n' "<prID>: PR number"
-	printf '\t%s\n' "<REMOTE>: GitHub remote that the PR targets (default: 'origin')"
-	printf '\t%s\n' "-h, --help: Prints help"
-	printf '\t%s\n' "-v, --version: Prints version"
-	printf '\t%s\n' "-p, --protocol: force using a specific protocol for the new remote.
+    printf 'Usage: %s [-h|--help] [-v|--version] [-p|--protocol <arg>] [-f|--(no-)force] [--] <prID> [<REMOTE>]\n' "$0"
+    printf '\t%s\n' "<prID>: PR number"
+    printf '\t%s\n' "<REMOTE>: GitHub remote that the PR targets (default: 'origin')"
+    printf '\t%s\n' "-h, --help: Prints help"
+    printf '\t%s\n' "-v, --version: Prints version"
+    printf '\t%s\n' "-p, --protocol: force using a specific protocol for the new remote.
 		Supported values are 'ssh' and 'https'.
 		By default, the same protocol is used as in REMOTE (no default)"
-	printf '\t%s\n' "-f, --force, --no-force: overwrite the branch if it exists (off by default)"
-	printf '\n%s\n' "$(description)"
+    printf '\t%s\n' "-f, --force, --no-force: overwrite the branch if it exists (off by default)"
+    printf '\n%s\n' "$(description)"
 }
 
 
 parse_commandline()
 {
-	_positionals_count=0
-	local _key
-	while test $# -gt 0
-	do
-		_key="$1"
-		if test "$_key" = '--'
-		then
-			shift
-			test $# -gt 0 || break
-			_positionals+=("$@")
-			_positionals_count=$((_positionals_count + $#))
-			shift $(($# - 1))
-			_last_positional="$1"
-			break
-		fi
-		case "$_key" in
-			-h|--help)
-				print_help
-				exit 0
-				;;
-			-h*)
-				print_help
-				exit 0
-				;;
-			-v|--version)
-				echo "git-prw $ts"
-				exit 0
-				;;
-			-v*)
-				echo "git-prw $ts"
-				exit 0
-				;;
-			-p|--protocol)
-				test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
-				_arg_protocol="$2"
-				shift
-				;;
-			--protocol=*)
-				_arg_protocol="${_key##--protocol=}"
-				;;
-			-p*)
-				_arg_protocol="${_key##-p}"
-				;;
-			-f|--no-force|--force)
-				_arg_force="on"
-				test "${1:0:5}" = "--no-" && _arg_force="off"
-				;;
-			-f*)
-				_arg_force="on"
-				_next="${_key##-f}"
-				if test -n "$_next" -a "$_next" != "$_key"
-				then
-					{ begins_with_short_option "$_next" && shift && set -- "-f" "-${_next}" "$@"; } || die "The short option '$_key' can't be decomposed to ${_key:0:2} and -${_key:2}, because ${_key:0:2} doesn't accept value and '-${_key:2:1}' doesn't correspond to a short option."
-				fi
-				;;
-			*)
-				_last_positional="$1"
-				_positionals+=("$_last_positional")
-				_positionals_count=$((_positionals_count + 1))
-				;;
-		esac
-		shift
-	done
+    _positionals_count=0
+    local _key
+    while test $# -gt 0
+    do
+        _key="$1"
+        if test "$_key" = '--'
+        then
+            shift
+            test $# -gt 0 || break
+            _positionals+=("$@")
+            _positionals_count=$((_positionals_count + $#))
+            shift $(($# - 1))
+            _last_positional="$1"
+            break
+        fi
+        case "$_key" in
+            -h|--help)
+                print_help
+                exit 0
+                ;;
+            -h*)
+                print_help
+                exit 0
+                ;;
+            -v|--version)
+                echo "git-prw $ts"
+                exit 0
+                ;;
+            -v*)
+                echo "git-prw $ts"
+                exit 0
+                ;;
+            -p|--protocol)
+                test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
+                _arg_protocol="$2"
+                shift
+                ;;
+            --protocol=*)
+                _arg_protocol="${_key##--protocol=}"
+                ;;
+            -p*)
+                _arg_protocol="${_key##-p}"
+                ;;
+            -f|--no-force|--force)
+                _arg_force="on"
+                test "${1:0:5}" = "--no-" && _arg_force="off"
+                ;;
+            -f*)
+                _arg_force="on"
+                _next="${_key##-f}"
+                if test -n "$_next" -a "$_next" != "$_key"
+                then
+                    { begins_with_short_option "$_next" && shift && set -- "-f" "-${_next}" "$@"; } || die "The short option '$_key' can't be decomposed to ${_key:0:2} and -${_key:2}, because ${_key:0:2} doesn't accept value and '-${_key:2:1}' doesn't correspond to a short option."
+                fi
+                ;;
+            *)
+                _last_positional="$1"
+                _positionals+=("$_last_positional")
+                _positionals_count=$((_positionals_count + 1))
+                ;;
+        esac
+        shift
+    done
 }
 
 
 handle_passed_args_count()
 {
-	local _required_args_string="'prID'"
-	test "${_positionals_count}" -ge 1 || _PRINT_HELP=yes die "FATAL ERROR: Not enough positional arguments - we require between 1 and 2 (namely: $_required_args_string), but got only ${_positionals_count}." 1
-	test "${_positionals_count}" -le 2 || _PRINT_HELP=yes die "FATAL ERROR: There were spurious positional arguments --- we expect between 1 and 2 (namely: $_required_args_string), but got ${_positionals_count} (the last one was: '${_last_positional}')." 1
+    local _required_args_string="'prID'"
+    test "${_positionals_count}" -ge 1 || _PRINT_HELP=yes die "FATAL ERROR: Not enough positional arguments - we require between 1 and 2 (namely: $_required_args_string), but got only ${_positionals_count}." 1
+    test "${_positionals_count}" -le 2 || _PRINT_HELP=yes die "FATAL ERROR: There were spurious positional arguments --- we expect between 1 and 2 (namely: $_required_args_string), but got ${_positionals_count} (the last one was: '${_last_positional}')." 1
 }
 
 
 assign_positional_args()
 {
-	local _positional_name _shift_for=$1
-	_positional_names="_arg_prid _arg_remote "
+    local _positional_name _shift_for=$1
+    _positional_names="_arg_prid _arg_remote "
 
-	shift "$_shift_for"
-	for _positional_name in ${_positional_names}
-	do
-		test $# -gt 0 || break
-		eval "$_positional_name=\${1}" || die "Error during argument parsing, possibly an Argbash bug." 1
-		shift
-	done
+    shift "$_shift_for"
+    for _positional_name in ${_positional_names}
+    do
+        test $# -gt 0 || break
+        eval "$_positional_name=\${1}" || die "Error during argument parsing, possibly an Argbash bug." 1
+        shift
+    done
 }
 
 parse_commandline "$@"
