Rewrite using the Argbash framework

diff --git a/bin/git-prw b/bin/git-prw
--- a/bin/git-prw
+++ b/bin/git-prw
@@ -4,40 +4,21 @@ set -euo pipefail
 #
 # Licensed under the MIT license <https://opensource.org/licenses/MIT>
 #
-ts="Time-stamp: <2022-03-05 12:31:12 emartin>"; ts=${ts#Time-stamp: }
-
-die_hard() {
-    echo -e "$@" >&2
-    exit 1
-}
-
-usage() {
-    cat >&2 <<EOF
-git-prw $ts
-
-Facility to fetch a read/write branch from a GitHub repo Pull Request.
-
-Usage:
-  git prw [--ssh|--https] <ID> [<REMOTE>] [-f]
-
+ts="Time-stamp: <2026-06-30 22:04:10 erik>"; ts=${ts#Time-stamp: }
+description() {
+cat <<EOF
 Example:
   git prw 390 upstream
 
 Summary:
-  If the REMOTE argument is omitted, it defaults to "origin".
-  REMOTE must point to a GitHub repository.
-
-  This command checks out the branch named "pr/ID". If it doesn't exist
-  yet, it fetches the source branch for the PR #ID in the REMOTE repo
+  This command checks out the branch named "pr/\$prID". If it doesn't exist
+  yet, it fetches the source branch for this PR in the REMOTE repo
   and sets its upstream branch so that one can push to the PR branch.
   It reuses (if applicable) an existing remote
-  matching that URL, or creates a remote named REMOTE-fork-for-pr-ID.
-  The URL to use it picked for the same protocol as what REMOTE uses;
-  passing --ssh or --https forces a specific protocol.
+  matching that URL, or creates a remote named REMOTE-fork-for-pr-\$prID.
 
-  Flag -f overwrites the local branch pr/ID even if it already exists.
   In general, it is a good idea to pass flag -f, unless we already ran
-  "git pr ID REMOTE" and did commits in the local branch pr/ID.
+  "git pr prID REMOTE" and did commits in the local branch pr/ID.
 
   It requires curl <https://curl.se/> and (optionally) jq.
 
@@ -51,6 +32,164 @@ Credits:
   distributed under the MIT license <//opensource.org/licenses/MIT>.
 EOF
 }
+#
+# ARG_HELP([Facility to fetch a read/write branch from a GitHub repo Pull Request (PR).\n],[$(description)])
+# ARG_VERSION([echo "git-prw $ts"])
+# ARG_OPTIONAL_SINGLE([protocol],[p],[force using a specific protocol for the new remote.\nSupported values are 'ssh' and 'https'.\nBy default, the same protocol is used as in REMOTE])
+# ARG_OPTIONAL_BOOLEAN([force],[f],[overwrite the branch if it exists])
+# ARG_POSITIONAL_SINGLE([prID],[PR number],[])
+# ARG_POSITIONAL_SINGLE([REMOTE],[GitHub remote that the PR targets],[origin])
+# ARG_POSITIONAL_DOUBLEDASH([])
+# ARG_DEFAULTS_POS([])
+# ARGBASH_GO()
+# needed because of Argbash --> m4_ignore([
+### START OF CODE GENERATED BY Argbash v2.11.0 one line above ###
+# Argbash is a bash code generator used to get arguments parsing right.
+# Argbash is FREE SOFTWARE, see https://argbash.dev for more info
+# Generated online by https://argbash.dev/generate
+
+
+die()
+{
+	local _ret="${2:-1}"
+	test "${_PRINT_HELP:-no}" = yes && print_help >&2
+	echo "$1" >&2
+	exit "${_ret}"
+}
+
+
+begins_with_short_option()
+{
+	local first_option all_short_options='hvpf'
+	first_option="${1:0:1}"
+	test "$all_short_options" = "${all_short_options/$first_option/}" && return 1 || return 0
+}
+
+# THE DEFAULTS INITIALIZATION - POSITIONALS
+_positionals=()
+_arg_prid=
+_arg_remote="origin"
+# THE DEFAULTS INITIALIZATION - OPTIONALS
+_arg_protocol=
+_arg_force="off"
+
+
+print_help()
+{
+	printf '%s\n' "Facility to fetch a read/write branch from a GitHub repo Pull Request (PR).
+"
+	printf 'Usage: %s [-h|--help] [-v|--version] [-p|--protocol <arg>] [-f|--(no-)force] [--] <prID> [<REMOTE>]\n' "git prw"
+	printf '\t%s\n' "<prID>: PR number"
+	printf '\t%s\n' "<REMOTE>: GitHub remote that the PR targets (default: 'origin')"
+	printf '\t%s\n' "-h, --help: Prints help"
+	printf '\t%s\n' "-v, --version: Prints version"
+	printf '\t%s\n' "-p, --protocol: force using a specific protocol for the new remote.
+		Supported values are 'ssh' and 'https'.
+		By default, the same protocol is used as in REMOTE (no default)"
+	printf '\t%s\n' "-f, --force, --no-force: overwrite the branch if it exists (off by default)"
+	printf '\n%s\n' "$(description)"
+}
+
+
+parse_commandline()
+{
+	_positionals_count=0
+	local _key
+	while test $# -gt 0
+	do
+		_key="$1"
+		if test "$_key" = '--'
+		then
+			shift
+			test $# -gt 0 || break
+			_positionals+=("$@")
+			_positionals_count=$((_positionals_count + $#))
+			shift $(($# - 1))
+			_last_positional="$1"
+			break
+		fi
+		case "$_key" in
+			-h|--help)
+				print_help
+				exit 0
+				;;
+			-h*)
+				print_help
+				exit 0
+				;;
+			-v|--version)
+				echo "git-prw $ts"
+				exit 0
+				;;
+			-v*)
+				echo "git-prw $ts"
+				exit 0
+				;;
+			-p|--protocol)
+				test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
+				_arg_protocol="$2"
+				shift
+				;;
+			--protocol=*)
+				_arg_protocol="${_key##--protocol=}"
+				;;
+			-p*)
+				_arg_protocol="${_key##-p}"
+				;;
+			-f|--no-force|--force)
+				_arg_force="on"
+				test "${1:0:5}" = "--no-" && _arg_force="off"
+				;;
+			-f*)
+				_arg_force="on"
+				_next="${_key##-f}"
+				if test -n "$_next" -a "$_next" != "$_key"
+				then
+					{ begins_with_short_option "$_next" && shift && set -- "-f" "-${_next}" "$@"; } || die "The short option '$_key' can't be decomposed to ${_key:0:2} and -${_key:2}, because ${_key:0:2} doesn't accept value and '-${_key:2:1}' doesn't correspond to a short option."
+				fi
+				;;
+			*)
+				_last_positional="$1"
+				_positionals+=("$_last_positional")
+				_positionals_count=$((_positionals_count + 1))
+				;;
+		esac
+		shift
+	done
+}
+
+
+handle_passed_args_count()
+{
+	local _required_args_string="'prID'"
+	test "${_positionals_count}" -ge 1 || _PRINT_HELP=yes die "FATAL ERROR: Not enough positional arguments - we require between 1 and 2 (namely: $_required_args_string), but got only ${_positionals_count}." 1
+	test "${_positionals_count}" -le 2 || _PRINT_HELP=yes die "FATAL ERROR: There were spurious positional arguments --- we expect between 1 and 2 (namely: $_required_args_string), but got ${_positionals_count} (the last one was: '${_last_positional}')." 1
+}
+
+
+assign_positional_args()
+{
+	local _positional_name _shift_for=$1
+	_positional_names="_arg_prid _arg_remote "
+
+	shift "$_shift_for"
+	for _positional_name in ${_positional_names}
+	do
+		test $# -gt 0 || break
+		eval "$_positional_name=\${1}" || die "Error during argument parsing, possibly an Argbash bug." 1
+		shift
+	done
+}
+
+parse_commandline "$@"
+handle_passed_args_count
+assign_positional_args 1 "${_positionals[@]}"
+
+# OTHER STUFF GENERATED BY Argbash
+
+### END OF CODE GENERATED BY Argbash (sortof) ### ])
+# [ <-- needed because of Argbash
+
 
 get_remote_user_repo() {
     # ARG $1: "origin"
@@ -78,38 +217,38 @@ get_pr_json() {
     if [[ $repo =~ ^[^/]+/[^/]+$ ]]; then
         curl -fsSH "Accept: application/vnd.github.v3+json" "https://api.github.com/repos/$repo/pulls/$prid"
     else
-        die_hard "git-prw: Assert failed in get_pr_json(); incorrect CLI args?"
+        die "$0: Assert failed in get_pr_json(); incorrect CLI args?"
     fi
 }
 
 get_src_url_grep() {
     # ARG $1: JSON key, alphabetic
     local key=${1:?}
-    grep -e '"'$key'"' | head -n1 | sed -e 's/^.*"'$key'":[[:space:]]*"//; s/",[[:space:]]*$//'
+    grep -e '"'"$key"'"' | head -n1 | sed -e 's/^.*"'"$key"'":[[:space:]]*"//; s/",[[:space:]]*$//'
 }
 
 get_src_url_jq() {
     # ARG $1: JSON key, alphabetic
     local key=${1:?}
-    jq -r '.head.repo.'$key
+    jq -r ".head.repo.$key"
 }
 
 get_src_url() {
     # ARG $1: protocol
     # OUTPUT: Git URL
     local key
-    
+
     case ${1:?} in
         ssh) key=ssh_url;;
         https) key=clone_url;;
-        *) die_hard "unknown protocol: '$1'";;
+        *) die "unknown protocol: '$1'";;
     esac
-    
+
     if command -v jq >/dev/null; then
-        get_src_url_jq $key  # better
+        get_src_url_jq "$key"  # better
     else
         echo >&2 "Cannot find jq; fall back to grep/head/sed..."
-        get_src_url_grep $key
+        get_src_url_grep "$key"
     fi
 }
 
@@ -163,66 +302,32 @@ detect_protocol() {
     # ARG $1: remote URL
     # RETURN: ssh or https
     local remote=${1:?}
-    local remote_url=$(git remote get-url "$remote")
+    local remote_url
+    remote_url=$(git remote get-url "$remote")
     [[ $remote_url == "https://"* ]] && { echo "https"; return; }
     # https://stackoverflow.com/questions/31801271/what-are-the-supported-git-url-formats
     # How Git extracts username:password, see url_normalize in urlmatch.c . Laxer than RFC 3986
     [[ $remote_url == "ssh://"* || $remote_url =~ ^[^/?#@]+@.+ ]] && { echo "ssh"; return; }
-    die_hard "cannot detect protocol for '$remote_url'"
+    die "cannot detect protocol for '$remote_url'"
 }
 
 main() {
-    local prid
-    local remote
-    local json
-    local protocol=
+    local remote="$_arg_remote"
+    local prid="$_arg_prid"
+    local protocol="$_arg_protocol"
+    local force="$_arg_force"
     local remote_url
     local unique_suggested_name
     local tracking_remote
     local ref
     local tracking_branch
-    local force=false
-    local args
-    local k
-    # Based on https://mywiki.wooledge.org/ComplexOptionParsing#util-linux.27s_special_getopt
-    # Take advantage of util-linux `getopt's advanced parsing if available
-    if getopt -T &>/dev/null && false || (( $? == 4 )) ; then
-        eval set -- "$(getopt -o f -l ssh,https -- "$@")"
-    else
-        # Process optional CLI option -f, which can be anywhere
-        args=("${@}")
-        for (( k=0; k < $#; k++ )); do
-            if [ "${args[$k]}" = "-f" ]; then
-                force=true
-                unset args["$k"]
-            fi
-        done
-        set -- "${args[@]}"
-    fi
-    while (($# > 0)); do
-        case $1 in
-            --ssh) protocol="ssh";;
-            --https) protocol="https";;
-            -f) force=true;;
-            --) shift; break;;
-            *) break;;
-        esac
-        shift
-    done
-    
-    if [ $# -lt 1 ]; then
-        usage
-        exit 0
-    fi
 
-    prid=$1
-    remote=${2:-origin}
-    
+
     if [[ -z $protocol ]]; then
         protocol=$(detect_protocol "$remote")
     fi
 
-    if already_exists pr/"$prid" && [ "$force" = false ]; then
+    if already_exists pr/"$prid" && [ "$force" = on ]; then
         echo >&2 "Preserving branch pr/$prid. To overwrite, use the -f flag."
     else
         echo >&2 "Overwriting branch pr/$prid..."
@@ -241,3 +346,5 @@ main() {
 }
 
 main "$@"
+
+# ] <-- needed because of Argbash
